// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI78rTiMLIloM55X8N_9Oo58fd87vOs0g',
    appId: '1:545825727730:web:f00ac4ee8d3bb05aeb9c6b',
    messagingSenderId: '545825727730',
    projectId: 'newfirebaseproject-82c04',
    authDomain: 'newfirebaseproject-82c04.firebaseapp.com',
    storageBucket: 'newfirebaseproject-82c04.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc9OOwtt6ChxTUmb95HKy6PP4BQHDLNkg',
    appId: '1:545825727730:android:58b8e13f7de86a7ceb9c6b',
    messagingSenderId: '545825727730',
    projectId: 'newfirebaseproject-82c04',
    storageBucket: 'newfirebaseproject-82c04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAofixlK5p0TOHiSUjWfs2Gka255kchgME',
    appId: '1:545825727730:ios:8add236f200a679deb9c6b',
    messagingSenderId: '545825727730',
    projectId: 'newfirebaseproject-82c04',
    storageBucket: 'newfirebaseproject-82c04.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAofixlK5p0TOHiSUjWfs2Gka255kchgME',
    appId: '1:545825727730:ios:8add236f200a679deb9c6b',
    messagingSenderId: '545825727730',
    projectId: 'newfirebaseproject-82c04',
    storageBucket: 'newfirebaseproject-82c04.firebasestorage.app',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI78rTiMLIloM55X8N_9Oo58fd87vOs0g',
    appId: '1:545825727730:web:248fe7a996c449eaeb9c6b',
    messagingSenderId: '545825727730',
    projectId: 'newfirebaseproject-82c04',
    authDomain: 'newfirebaseproject-82c04.firebaseapp.com',
    storageBucket: 'newfirebaseproject-82c04.firebasestorage.app',
  );
}
